update /test/e2e/concurrency/fail-fast/expected.yaml & add README.md to introduce how to use e2e-test
apache/skywalking-infra-e2e pull request #119
Opened 2023-09-19 01:04 UTC by chunriyeqiongsaigao

1. update /test/e2e/concurrency/fail-fast/expected.yaml : use 'subtractor' in /test/e2e/concurrency/failfast/expected.yaml .
2. add README.md to introduce how to use e2e-test (still thinging about it, haven't created any files yet).

2023-09-19 01:06 UTC, wu-sheng commented
I think you missed the doc update?

2023-09-19 01:09 UTC, chunriyeqiongsaigao commented
> I think you missed the doc update?

Thank you very much for the reminder. I will update this doc once I have finished writing it.

2023-09-26 13:11 UTC, wu-sheng commented
@fgksgf Please take a look.

2023-09-26 15:00 UTC, fgksgf commented on test/e2e/README.md
> +You can perform testing locally. And when you submit a pull request (PR), GitHub Actions will automatically run the tests.
You need also introduce how this work, such as the outer e2e and the inner e2e.

2023-09-26 15:01 UTC, fgksgf commented on test/e2e/README.md
> +- We add `&& sleep=5` in `query`of the last few cases, to make sure that there will be cases to be skipped.
This can be added as comments to related yaml files

2023-09-26 15:02 UTC, fgksgf commented on test/e2e/README.md
> +## Tips
One detailed example is enough, the purpose of the readme is to tell new contributors how to add new cases for their changes.

2023-10-25 12:26 UTC, fgksgf requested changes

2023-10-25 12:26 UTC, fgksgf commented on Makefile
> +	- ./bin/linux/e2e verify -c ./test/e2e/e2e.yaml
1. We should not assume that developers are using linux
2. Should be `run`, instead of `verify`

2023-10-25 12:26 UTC, fgksgf commented on test/e2e/README.md
> +We use the docker container of 'httpbin' as the SUT, which can receive the 'query' of E2E and return YAML data to E2E.After receiving the YAML data from 'httpbin', the E2E will compare the YAML data
In fact, `httpbin` is the SUT for the internal e2e, right? For the external e2e, the SUT is the internal e2e.

2023-10-25 12:26 UTC, fgksgf commented on test/e2e/README.md
> +We use the E2E(released version) to test E2E(dev version) of each mode. The E2E(released version) will compare the summary of E2E of each mode with the expected file. If the summary is as expected, t
I think this information is the most important in the doc, we need to tell readers earlier.

2023-10-25 12:26 UTC, fgksgf commented on test/e2e/README.md
> +after(add a new case named 'case-4'):
No need to use `before` and `after`, just one code block, and use comments to show the added case

2023-10-25 12:26 UTC, fgksgf commented on test/e2e/README.md
> +- entered the 'skywalking-infra-e2e' directory, use 'make e2e-test' to run the test locally
```suggestion
- You can use `make e2e-test` to run the test locally
```

2023-10-25 12:26 UTC, fgksgf commented on test/e2e/README.md
> +- you may need to split your PR to pass e2e tests in CI
Could you add some explanation?

2023-10-29 02:32 UTC, fgksgf approved these changes
LGTM, thanks for your contribution!

2023-10-29 02:32 UTC, fgksgf commented on test/e2e/README.md
> +- you may need to split your PR to pass e2e tests in CI
```suggestion
- You may need to split your PR to pass e2e tests in CI
```

2023-10-29 02:32 UTC, fgksgf approved these changes

2023-10-29 02:49 UTC, merged